In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [10]:
df_puerto = pd.read_csv('datosPuerto.csv')
df_puerto.head()

,Unnamed: 0,FECHA,AGRUP_MERCANCIA,TIPO_MERCANCIA,PARTIDA_ARANCELARIA,TIPO_ENVASE,CARGA_DESCARGA,PAIS_ORIGEN,PAIS_FINAL,PESO_KILOS
0,0,2007-01-22,1,1,2709A,4,D,IQ,ES,138283515
1,1,2007-01-22,1,1,2709A,4,D,RU,ES,101154523
2,2,2007-01-22,1,2,2710A,4,C,ES,ES,38831068
3,3,2007-01-22,1,2,2710A,4,C,ES,US,56224084
4,4,2007-01-22,1,2,2710A,4,D,RU,ES,33789198

In [11]:
#Filtramos las partidas arancelarias para que solo salgan los capitulos
df_puerto['capitulo'] = df_puerto['PARTIDA_ARANCELARIA'].astype(str).str[:2]

In [12]:
#FIltramos para que solo sean importanciones y exportaciones a Paises bajos
df_puerto = df_puerto[((df_puerto['PAIS_ORIGEN'] == 'NL') & (df_puerto['PAIS_FINAL'] == 'ES')) | ((df_puerto['PAIS_ORIGEN'] == 'ES') & (df_puerto['PAIS_FINAL'] == 'NL'))]

In [13]:
#Agrupamos los kilos por pais y capitulo, y los ordenamos de mayor a menor para ver los capitulos mas importantes
ranking_puerto = df_puerto.groupby(['PAIS_ORIGEN', 'capitulo'])['PESO_KILOS'].sum().reset_index()
ranking_puerto = ranking_puerto.sort_values(by='PESO_KILOS', ascending=False)

In [14]:
ranking_puerto

    PAIS_ORIGEN capitulo  PESO_KILOS
25           ES       27  6198887611
157          NL       72  4118701260
23           ES       25  2562967346
113          NL       27  2515759815
27           ES       29  1451349227
..          ...      ...         ...
152          NL       67        6431
145          NL       60        5231
172          NL       88        4874
127          NL       41         621
12           ES       13           2

[183 rows x 3 columns]

In [15]:
#codigos_arancelarios_capitulos.pdf:

#CAPÍTULO 27:	Combustibles minerales, aceites minerales y productos de su destilación, materias bituminosas, ceras minerales.
#CAPÍTULO 72:	Fundición, hierro y acero
#CAPÍTULO 25:	Sal, azufre, tierras y piedras, yesos, cales y cementos. 
#CAPITULO 29:   Productos químicos orgánicos.

In [16]:
#Cargamos los datos para hacer la importancia del puerto de bilbao en españa pero solo con los capitulos importantes
euskadi = pd.read_excel("importaciones_exportaciones_euskadi.xlsx",sheet_name="Exportaciones")
puerto = pd.read_csv("datosPuerto.csv", decimal=",")

In [17]:
#Cambiamos la fecha a datetime y ponemos solo el año
puerto['FECHA'] = pd.to_datetime(puerto['FECHA'])
puerto['FECHA'] = puerto['FECHA'].dt.year

In [18]:
#Filtramos para que el periodo de años sea del 2009 al 2019(es hasta 2019 poprque el dataset de euskadi solo llega hasta 2019) y remplazamos los valores faltantes por 0
euskadi.copy()
euskadi_filtrado = euskadi[(euskadi["País"]== "Países Bajos")]
columnas_años = ["2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019"]
euskadi_filtrado[columnas_años] = (euskadi_filtrado[columnas_años].replace("-", 0))
euskadi_filtrado[columnas_años] = euskadi_filtrado[columnas_años].astype(float)

C:\Users\Win11 User\AppData\Local\Temp\ipykernel_8504\2482301886.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  euskadi_filtrado[columnas_años] = (euskadi_filtrado[columnas_años].replace("-", 0))
C:\Users\Win11 User\AppData\Local\Temp\ipykernel_8504\2482301886.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  euskadi_filtrado[columnas_años] = (euskadi_filtrado[columnas_años].replace("-", 0))
C:\Users\Win11 User\AppData\Local\Temp\ipykernel_8504\2482301886.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  euskadi_filtrado[columnas_años] = euskadi_filtrado[columnas_años].astype(float)

In [19]:
#Filtramos para que solo sea el puerto respecto a paises bajos

puerto_paisesbajos = puerto[(puerto["PAIS_FINAL"] == "NL") | (puerto["PAIS_ORIGEN"] == "NL")]

In [20]:
#Filtramos de nuevo para que solo salgan los capitulos
puerto_paisesbajos['capitulo'] = puerto_paisesbajos['PARTIDA_ARANCELARIA'].astype(str).str[:2]

C:\Users\Win11 User\AppData\Local\Temp\ipykernel_8504\2375631322.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  puerto_paisesbajos['capitulo'] = puerto_paisesbajos['PARTIDA_ARANCELARIA'].astype(str).str[:2]

In [21]:
puerto_paisesbajos

,Unnamed: 0,FECHA,AGRUP_MERCANCIA,TIPO_MERCANCIA,PARTIDA_ARANCELARIA,TIPO_ENVASE,CARGA_DESCARGA,PAIS_ORIGEN,PAIS_FINAL,PESO_KILOS,capitulo
20,20,2007,1,7,2901,4,C,ES,NL,1708492,29
23,23,2007,1,12,2703,5,D,NL,ES,48000,27
44,44,2007,2,13,7201,5,D,NL,ES,225060,72
49,49,2007,2,13,7202,5,D,NL,ES,124269,72
78,78,2007,2,13,7210A,5,D,NL,ES,25049,72
...,...,...,...,...,...,...,...,...,...,...,...
1366728,1366728,2024,9,39,8609T,5,C,NL,MA,12000,86
1366754,1366754,2024,9,39,8609T,5,D,ES,NL,30000,86
1366786,1366786,2024,9,39,8609T,5,D,NL,ES,3782000,86
1366787,1366787,2024,9,39,8609T,5,D,NL,GB,6500,86
1366788,1366788,2024,9,39,8609T,5,D,NL,SN,2000,86

In [22]:
#Cambiamos el numero de capitulo a int
puerto_paisesbajos["capitulo"]=puerto_paisesbajos["capitulo"].astype(int)

C:\Users\Win11 User\AppData\Local\Temp\ipykernel_8504\3066189565.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  puerto_paisesbajos["capitulo"]=puerto_paisesbajos["capitulo"].astype(int)

In [23]:
#Filtramos para que solo sean las exportaciones y importaciones de los capitulos mencionados
capitulos = [25, 27, 29, 72]
codigos = ["25", "27", "29", "72"]

euskadi_filtrado = euskadi_filtrado[euskadi_filtrado["Código_arancelario"].str.startswith(tuple(codigos))]

puerto_paisesbajos = puerto_paisesbajos[puerto_paisesbajos["capitulo"].isin(capitulos)]

In [24]:
#Hacemos la suma de las toneladas por año y lo pasamos a kilos
toneladas = euskadi_filtrado[euskadi_filtrado["Unidades"] == "Toneladas"]

exportaciones_por_año = toneladas[columnas_años].sum()

exportaciones_por_año = exportaciones_por_año*1000

print(exportaciones_por_año)

2009    2.911160e+08
2010    3.420500e+08
2011    4.460680e+08
2012    3.984770e+08
2013    6.915280e+08
2014    1.451152e+09
2015    9.354980e+08
2016    1.015488e+09
2017    1.007653e+09
2018    1.340692e+09
2019    1.077741e+09
dtype: float64

In [25]:
puerto_paisesbajos

,Unnamed: 0,FECHA,AGRUP_MERCANCIA,TIPO_MERCANCIA,PARTIDA_ARANCELARIA,TIPO_ENVASE,CARGA_DESCARGA,PAIS_ORIGEN,PAIS_FINAL,PESO_KILOS,capitulo
20,20,2007,1,7,2901,4,C,ES,NL,1708492,29
23,23,2007,1,12,2703,5,D,NL,ES,48000,27
44,44,2007,2,13,7201,5,D,NL,ES,225060,72
49,49,2007,2,13,7202,5,D,NL,ES,124269,72
78,78,2007,2,13,7210A,5,D,NL,ES,25049,72
...,...,...,...,...,...,...,...,...,...,...,...
1364108,1364108,2024,5,17,2918,5,D,NL,ES,24000,29
1364113,1364113,2024,5,17,2921,5,D,NL,ES,181420,29
1364115,1364115,2024,5,17,2922,5,D,NL,ES,78640,29
1364121,1364121,2024,5,17,2930,5,D,NL,ES,40287,29
1364137,1364137,2024,5,17,2940,5,D,NL,ES,82000,29

In [26]:
#FIltramos solo paises bajos y españa
exp_puerto = puerto_paisesbajos[(puerto_paisesbajos["PAIS_ORIGEN"] == "ES") & (puerto_paisesbajos["PAIS_FINAL"] == "NL")]

In [27]:
#agrupamos los kilos pòr años
exp_puerto = exp_puerto.groupby("FECHA")["PESO_KILOS"].sum()

In [28]:
#Filtramos solo de 2009 a 2019
exp_puerto=exp_puerto.loc[2009:2019]

In [29]:
exp_puerto

FECHA
2009    321621928
2010    355902090
2011    655892861
2012    423772213
2013    765435985
2014    831223559
2015    466815575
2016    672108920
2017    778407585
2018    722548265
2019    881720438
Name: PESO_KILOS, dtype: int64

In [30]:
exportaciones_por_año.astype(int)

2009     291116000
2010     342050000
2011     446068000
2012     398477000
2013     691528000
2014    1451152000
2015     935498000
2016    1015488000
2017    1007653000
2018    1340692000
2019    1077741000
dtype: int64

In [31]:
#Lo pasamos a una serie para que sea mas sencillo el calculo del porcentaje
exp_puerto=pd.Series({
    2009: 321621928,
    2010: 355902090,
    2011: 655892861,
    2012: 423772213,
    2013: 765435985,
    2014: 831223559,
    2015: 466815575,
    2016: 672108920,
    2017: 778407585,
    2018: 722548265,
    2019: 881720438
})
exportaciones_por_año=pd.Series({
    2009: 291116000,
    2010: 342050000,
    2011: 446068000,
    2012: 398477000,
    2013: 691528000,
    2014: 1451152000,
    2015: 935498000,
    2016: 1015488000,
    2017: 1007653000,
    2018: 1340692000,
    2019: 1077741000

})

In [32]:
#Calculamos la importancia del puerto de bilbao respecto a euskadi(DA mas de 100 porque el dataset de euskadi tiene un error en la recogida de datos)
porcentaje_imp = (exp_puerto / exportaciones_por_año) * 100
porcentaje_imp

2009    110.478960
2010    104.049727
2011    147.038761
2012    106.347973
2013    110.687634
2014     57.280255
2015     49.900222
2016     66.185806
2017     77.249568
2018     53.893681
2019     81.811905
dtype: float64