In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [ ]:
#cargamos los datos
df_puerto = pd.read_csv('datosPuerto.csv')
df_puerto.head()

,Unnamed: 0,FECHA,AGRUP_MERCANCIA,TIPO_MERCANCIA,PARTIDA_ARANCELARIA,TIPO_ENVASE,CARGA_DESCARGA,PAIS_ORIGEN,PAIS_FINAL,PESO_KILOS
0,0,2007-01-22,1,1,2709A,4,D,IQ,ES,138283515
1,1,2007-01-22,1,1,2709A,4,D,RU,ES,101154523
2,2,2007-01-22,1,2,2710A,4,C,ES,ES,38831068
3,3,2007-01-22,1,2,2710A,4,C,ES,US,56224084
4,4,2007-01-22,1,2,2710A,4,D,RU,ES,33789198

In [ ]:
#Filtramos las partidas arancelarias para que solo salgan los capitulos
df_puerto['capitulo'] = df_puerto['PARTIDA_ARANCELARIA'].astype(str).str[:2]

In [ ]:
#FIltramos para que solo sean importanciones y exportaciones a Paises bajos
df_puerto = df_puerto[((df_puerto['PAIS_ORIGEN'] == 'NL') & (df_puerto['PAIS_FINAL'] == 'ES')) | ((df_puerto['PAIS_ORIGEN'] == 'ES') & (df_puerto['PAIS_FINAL'] == 'NL'))]

In [ ]:
#Agrupamos los kilos por pais y capitulo, y los ordenamos de mayor a menor para ver los capitulos mas importantes
ranking_puerto = df_puerto.groupby(['PAIS_ORIGEN', 'capitulo'])['PESO_KILOS'].sum().reset_index()
ranking_puerto = ranking_puerto.sort_values(by='PESO_KILOS', ascending=False)

In [30]:
ranking_puerto

    PAIS_ORIGEN capitulo  PESO_KILOS
25           ES       27  6198887611
157          NL       72  4118701260
23           ES       25  2562967346
113          NL       27  2515759815
27           ES       29  1451349227
..          ...      ...         ...
152          NL       67        6431
145          NL       60        5231
172          NL       88        4874
127          NL       41         621
12           ES       13           2

[183 rows x 3 columns]

In [31]:
#codigos_arancelarios_capitulos.pdf:

#CAPÍTULO 27:	Combustibles minerales, aceites minerales y productos de su destilación, materias bituminosas, ceras minerales.
#CAPÍTULO 72:	Fundición, hierro y acero
#CAPÍTULO 25:	Sal, azufre, tierras y piedras, yesos, cales y cementos. 
#CAPITULO 29:   Productos químicos orgánicos.

In [ ]:
#Cargamos los datos para hacer la importancia del puerto de bilbao en españa pero solo con los capitulos importantes
euskadi = pd.read_excel("importaciones_exportaciones_euskadi.xlsx",sheet_name="Importaciones")
puerto = pd.read_csv("datosPuerto.csv", decimal=",")

In [ ]:
#Cambiamos la fecha a datetime y ponemos solo el año
puerto['FECHA'] = pd.to_datetime(puerto['FECHA'])
puerto['FECHA'] = puerto['FECHA'].dt.year

In [ ]:
#Filtramos para que el periodo de años sea del 2009 al 2019(es hasta 2019 poprque el dataset de euskadi solo llega hasta 2019) y remplazamos los valores faltantes por 0
euskadi.copy()
euskadi_filtrado = euskadi[(euskadi["País"]== "Países Bajos")]
columnas_años = ["2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019"]
euskadi_filtrado[columnas_años] = (euskadi_filtrado[columnas_años].replace("-", 0))
euskadi_filtrado[columnas_años] = euskadi_filtrado[columnas_años].astype(float)

C:\Users\Win11 User\AppData\Local\Temp\ipykernel_25096\1579831421.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  euskadi_filtrado[columnas_años] = (euskadi_filtrado[columnas_años].replace("-", 0))
C:\Users\Win11 User\AppData\Local\Temp\ipykernel_25096\1579831421.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  euskadi_filtrado[columnas_años] = (euskadi_filtrado[columnas_años].replace("-", 0))
C:\Users\Win11 User\AppData\Local\Temp\ipykernel_25096\1579831421.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  euskadi_filtrado[columnas_años] = euskadi_filtrado[columnas_años].astype(float)

,País,Código_arancelario,Unidades,1990,1991,1992,1993,1994,1995,1996,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
16830,Países Bajos,00 No clasificados,Toneladas,-,-,-,0,-,-,-,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16831,Países Bajos,01 Animales vivos,Toneladas,176,125,180,-,29,-,4,...,18.0,4.0,0.0,0.0,1.0,9.0,8.0,53.0,501.0,78.0
16832,Países Bajos,02 Carnes y despojos comestibles,Toneladas,1774,1280,850,945,958,1457,1441,...,1165.0,1328.0,1192.0,1124.0,2358.0,1790.0,1650.0,1250.0,2044.0,4001.0
16833,Países Bajos,03 Pescados,Toneladas,1770,1634,1131,693,1848,749,569,...,1704.0,1648.0,1153.0,1344.0,1196.0,1103.0,1395.0,1904.0,2356.0,2755.0
16834,Países Bajos,04 Productos lácteos y huevos,Toneladas,136,934,848,1745,1496,978,451,...,1143.0,982.0,2392.0,1607.0,1615.0,1648.0,1668.0,1743.0,1174.0,1238.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16924,Países Bajos,95 Juguetes y artí. para recreo,Toneladas,36,35,52,25,36,26,50,...,23.0,32.0,24.0,108.0,182.0,137.0,420.0,572.0,446.0,219.0
16925,Países Bajos,96 Manufacturas diversas,Toneladas,39,4,1,4,1,0,3,...,3.0,5.0,842.0,1286.0,1333.0,1773.0,1208.0,1285.0,1466.0,1197.0
16926,Países Bajos,97 Objetos de arte,Toneladas,0,0,-,-,-,-,-,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16927,Países Bajos,98 Expo. conjuntos industriales,Toneladas,-,-,-,-,-,-,-,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16928,Países Bajos,99 No clasificados,Toneladas,20,0,48,-,0,0,-,...,27.0,195.0,169.0,0.0,0.0,0.0,0.0,0.0,262.0,51.0

In [ ]:
#Filtramos para que solo sea el puerto respecto a paises bajos
puerto_paisesbajos = puerto[(puerto["PAIS_FINAL"] == "NL") | (puerto["PAIS_ORIGEN"] == "NL")]

In [ ]:
#Filtrammos de nuevo para que solo salgan los capitulos
puerto_paisesbajos['capitulo'] = puerto_paisesbajos['PARTIDA_ARANCELARIA'].astype(str).str[:2]

C:\Users\Win11 User\AppData\Local\Temp\ipykernel_25096\3420023949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  puerto_paisesbajos['capitulo'] = puerto_paisesbajos['PARTIDA_ARANCELARIA'].astype(str).str[:2]

In [37]:
puerto_paisesbajos

,Unnamed: 0,FECHA,AGRUP_MERCANCIA,TIPO_MERCANCIA,PARTIDA_ARANCELARIA,TIPO_ENVASE,CARGA_DESCARGA,PAIS_ORIGEN,PAIS_FINAL,PESO_KILOS,capitulo
20,20,2007,1,7,2901,4,C,ES,NL,1708492,29
23,23,2007,1,12,2703,5,D,NL,ES,48000,27
44,44,2007,2,13,7201,5,D,NL,ES,225060,72
49,49,2007,2,13,7202,5,D,NL,ES,124269,72
78,78,2007,2,13,7210A,5,D,NL,ES,25049,72
...,...,...,...,...,...,...,...,...,...,...,...
1366728,1366728,2024,9,39,8609T,5,C,NL,MA,12000,86
1366754,1366754,2024,9,39,8609T,5,D,ES,NL,30000,86
1366786,1366786,2024,9,39,8609T,5,D,NL,ES,3782000,86
1366787,1366787,2024,9,39,8609T,5,D,NL,GB,6500,86
1366788,1366788,2024,9,39,8609T,5,D,NL,SN,2000,86

In [ ]:
#Cambiamos el numero de capitulo a int
puerto_paisesbajos["capitulo"]=puerto_paisesbajos["capitulo"].astype(int)

C:\Users\Win11 User\AppData\Local\Temp\ipykernel_25096\3231879007.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  puerto_paisesbajos["capitulo"]=puerto_paisesbajos["capitulo"].astype(int)

In [ ]:
#Filtramos para que solo sean las exportaciones y importaciones de los capitulos mencionados
capitulos = [25, 27, 29, 72]
codigos = ["25", "27", "29", "72"]

euskadi_filtrado = euskadi_filtrado[euskadi_filtrado["Código_arancelario"].str.startswith(tuple(codigos))]

puerto_paisesbajos = puerto_paisesbajos[puerto_paisesbajos["capitulo"].isin(capitulos)]

In [ ]:
#Hacemos la suma de las toneladas por año y lo pasamos a kilos
toneladas = euskadi_filtrado[euskadi_filtrado["Unidades"] == "Toneladas"]

importaciones_por_año = toneladas[columnas_años].sum()

importaciones_por_año = importaciones_por_año*1000

print(importaciones_por_año)

2009    487628000.0
2010    692902000.0
2011    455078000.0
2012    397200000.0
2013    187808000.0
2014    251330000.0
2015    409402000.0
2016    385262000.0
2017    386290000.0
2018    273190000.0
2019    364605000.0
dtype: float64

In [41]:
puerto_paisesbajos

,Unnamed: 0,FECHA,AGRUP_MERCANCIA,TIPO_MERCANCIA,PARTIDA_ARANCELARIA,TIPO_ENVASE,CARGA_DESCARGA,PAIS_ORIGEN,PAIS_FINAL,PESO_KILOS,capitulo
20,20,2007,1,7,2901,4,C,ES,NL,1708492,29
23,23,2007,1,12,2703,5,D,NL,ES,48000,27
44,44,2007,2,13,7201,5,D,NL,ES,225060,72
49,49,2007,2,13,7202,5,D,NL,ES,124269,72
78,78,2007,2,13,7210A,5,D,NL,ES,25049,72
...,...,...,...,...,...,...,...,...,...,...,...
1364108,1364108,2024,5,17,2918,5,D,NL,ES,24000,29
1364113,1364113,2024,5,17,2921,5,D,NL,ES,181420,29
1364115,1364115,2024,5,17,2922,5,D,NL,ES,78640,29
1364121,1364121,2024,5,17,2930,5,D,NL,ES,40287,29
1364137,1364137,2024,5,17,2940,5,D,NL,ES,82000,29

In [ ]:
#FIltramos solo paises bajos y españa
imp_puerto = puerto_paisesbajos[(puerto_paisesbajos["PAIS_ORIGEN"] == "NL") & (puerto_paisesbajos["PAIS_FINAL"] == "ES")]

In [ ]:
#agrupamos los kilos pòr años
imp_puerto = imp_puerto.groupby("FECHA")["PESO_KILOS"].sum()

In [ ]:
#Filtramos solo de 2009 a 2019
imp_puerto=imp_puerto.loc[2009:2019]

In [45]:
imp_puerto

FECHA
2009    558548317
2010    813118973
2011    495420144
2012    585389939
2013    413594698
2014    442602112
2015    318268047
2016    312975651
2017    347727342
2018    294974762
2019    445085736
Name: PESO_KILOS, dtype: int64

In [46]:
importaciones_por_año.astype(int)

2009    487628000
2010    692902000
2011    455078000
2012    397200000
2013    187808000
2014    251330000
2015    409402000
2016    385262000
2017    386290000
2018    273190000
2019    364605000
dtype: int64

In [ ]:
#Lo pasamos a una serie para que sea mas sencillo el calculo del porcentaje
imp_puerto=pd.Series({
    2009: 558548317,
    2010: 813118973,
    2011: 495420144,
    2012: 585389939,
    2013: 413594698,
    2014: 442602112,
    2015: 318268047,
    2016: 312975651,
    2017: 347727342,
    2018: 294974762,
    2019: 445085736
})
importaciones_por_año=pd.Series({
    2009: 487628000,
    2010: 692902000,
    2011: 455078000,
    2012: 397200000,
    2013: 187808000,
    2014: 251330000,
    2015: 409402000,
    2016: 385262000,
    2017: 386290000,
    2018: 273190000,
    2019: 364605000
})

In [ ]:
#Calculamos la importancia del puerto de bilbao respecto a euskadi(DA mas de 100 porque el dataset de euskadi tiene un error en la recogida de datos)
porcentaje_imp = (imp_puerto / importaciones_por_año) * 100
porcentaje_imp

2009    114.543939
2010    117.349780
2011    108.864886
2012    147.379139
2013    220.222087
2014    176.103972
2015     77.739739
2016     81.237093
2017     90.017174
2018    107.974216
2019    122.073404
dtype: float64